# These are supported funding model platforms

custom: ['paypal.me/tripbranch', 'https://donate.stripe.com/dR6dTTfii7DL02k288']
github: saisonxiang
patreon: waifuworks
ko_fi: ikemayfield
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: toki_mandrake
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
